name: ISOS Master Auto-Sync
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  drive_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Sync from Google Drive
        uses: nbadal/google-drive-github-sync@v1
        with:
          drive_id: ${{ secrets.GDRIVE_FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          target_folder: .
